#!/usr/bin/env python3
"""
add_text_to_illustrations.py

Overlay text (Finnish word, English translation, example sentence) on generated illustrations.
The text data is read from a JSON file generated by generate_word_list.py.

Creates a new image with:
  - Finnish word above the illustration
  - English translation below the Finnish word
  - Example sentence below the illustration

Usage:
  python add_text_to_illustrations.py --input-dir illustrations --words-json scripts/words_food.json --output-dir illustrations_with_text
"""
import argparse
import json
import os
import re
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


def load_words_data(words_json_path: str) -> dict:
    """Load word data from JSON file generated by generate_word_list.py.
    Returns a dict mapping word -> {translation, example, example_translation}.
    """
    words_map = {}
    try:
        with open(words_json_path, 'r', encoding='utf-8') as f:
            words_list = json.load(f)
            if isinstance(words_list, list):
                for item in words_list:
                    if isinstance(item, dict) and 'word' in item:
                        word = item['word'].lower()
                        # Clean up example sentence (remove parenthetical text which is often unwanted English translation)
                        raw_example = item.get('example', f'Tämä on {item["word"]}.')
                        clean_example = re.sub(r'\s*\(.*?\)', '', raw_example).strip()
                        
                        words_map[word] = {
                            'translation': item.get('translation', item['word']),
                            'example': clean_example,
                            'example_translation': item.get('example_translation', f'This is {item["word"]}.')
                        }
    except Exception as e:
        print(f"⚠️ Error loading words JSON {words_json_path}: {e}")
    return words_map


def add_text_overlay(
    image_path: str,
    word: str,
    output_path: str,
    words_data: dict,
    font_size: int = 24,
    padding: int = 40,
):
    """
    Add text overlay directly on the illustration image.
    Includes TikTok-safe margins to prevent content from being cut off in carousel view.
    Creates a new white canvas and scales down the illustration to fit within the safe area.
    """

    try:
        source_img = Image.open(image_path).convert("RGB")
    except Exception as e:
        print(f"❌ Error loading image {image_path}: {e}")
        return False

    # Original image dimensions
    orig_width, orig_height = source_img.size
    
    # Create a new white canvas at the same size
    img = Image.new("RGB", (orig_width, orig_height), (255, 255, 255))
    img_width, img_height = img.size
    
    # TikTok safe zone margins (15% top and bottom to avoid UI overlap)
    safe_margin_percent = 0.15
    safe_margin_top = int(img_height * safe_margin_percent)
    safe_margin_bottom = int(img_height * safe_margin_percent)
    safe_area_height = img_height - safe_margin_top - safe_margin_bottom
    
    # Extract the center square from the source image (the illustration part)
    # The source is 9:16 (e.g., 720x1280), so the illustration is the center 720x720 square
    square_size = min(orig_width, orig_height)  # Get the smaller dimension
    
    # Calculate crop box to extract center square
    if orig_width < orig_height:
        # Portrait: crop from top and bottom
        crop_left = 0
        crop_top = (orig_height - square_size) // 2
        crop_right = orig_width
        crop_bottom = crop_top + square_size
    else:
        # Landscape: crop from left and right
        crop_left = (orig_width - square_size) // 2
        crop_top = 0
        crop_right = crop_left + square_size
        crop_bottom = orig_height
    
    # Extract the square illustration
    illustration_square = source_img.crop((crop_left, crop_top, crop_right, crop_bottom))
    
    # Calculate scaled illustration size (leave room for text above and below)
    # Illustration should take up ~48% of the safe area height to leave more room for text
    illustration_scale = 0.48
    scaled_size = int(safe_area_height * illustration_scale)
    
    # Ensure it doesn't exceed available width
    max_width = img_width - (padding * 2)
    scaled_size = min(scaled_size, max_width)
    
    # Resize the square illustration proportionally (no distortion)
    scaled_illustration = illustration_square.resize(
        (scaled_size, scaled_size), 
        Image.Resampling.LANCZOS
    )
    
    # Calculate position to center the scaled illustration in the safe area
    # Leave room at top for word/translation, and more room at bottom for example sentences
    top_text_space = int(safe_area_height * 0.18)  # 18% for text above
    
    illustration_y = safe_margin_top + top_text_space
    illustration_x = (img_width - scaled_size) // 2
    
    # Paste the scaled illustration onto the white canvas
    img.paste(scaled_illustration, (illustration_x, illustration_y))
    
    # Store illustration bounds for text positioning
    illustration_top = illustration_y
    illustration_bottom = illustration_y + scaled_size

    # Get translation and example sentence
    word_lower = word.lower()
    if word_lower in words_data:
        translation = words_data[word_lower]['translation']
        example_sentence = words_data[word_lower]['example']
        example_sentence_translation = words_data[word_lower]['example_translation']
    else:
        translation = word
        example_sentence = f'Tämä on {word}.'
        example_sentence_translation = f'This is {word}.'

    draw = ImageDraw.Draw(img)

    # Try to load a clean, readable font (prioritize modern sans-serif fonts)
    font_paths = [
        # macOS fonts - modern and readable
        "/System/Library/Fonts/Avenir Next.ttc",
        "/System/Library/Fonts/SFNSRounded.ttf",
        "/System/Library/Fonts/Avenir.ttc",
        "/System/Library/Fonts/HelveticaNeue.ttc",
        # Windows fonts
        "C:\\Windows\\Fonts\\segoeui.ttf",
        "C:\\Windows\\Fonts\\arial.ttf",
        # Linux fonts
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    ]
    
    font = None
    font_small = None
    font_example = None  # Larger font for bottom example sentences
    used_font_path = None # Store the path that works

    for font_path in font_paths:
        try:
            font = ImageFont.truetype(font_path, font_size)
            font_small = ImageFont.truetype(font_path, int(font_size * 0.85))
            font_example = ImageFont.truetype(font_path, int(font_size * 1.15))  # 15% larger for examples
            used_font_path = font_path
            break
        except Exception:
            continue
    
    if font is None:
        font = ImageFont.load_default()
        font_small = font
        font_example = font


    def wrap_text(text, font, max_width):
        """Wrap text to fit within max_width. Returns list of lines."""
        words = text.split()
        lines = []
        current_line = []

        for word in words:
            current_line.append(word)
            line_text = " ".join(current_line)
            bbox = draw.textbbox((0, 0), line_text, font=font)
            line_width = bbox[2] - bbox[0]

            if line_width > max_width:
                current_line.pop()
                if current_line:
                    lines.append(" ".join(current_line))
                current_line = [word]

        if current_line:
            lines.append(" ".join(current_line))

        return lines

    def fit_text_to_one_line(text, font, max_width, start_size):
        """Adjust font size to fit text on one line, or return the text with smaller font."""
        target_width = max_width * 0.95 # Safety margin
        
        bbox = draw.textbbox((0, 0), text, font=font)
        text_width = bbox[2] - bbox[0]
        
        if text_width <= target_width:
            return text, font
        
        # Try progressively smaller font sizes
        current_size = int(start_size * 0.9)
        while current_size > 8:
            smaller_font = None
            if used_font_path:
                try:
                    smaller_font = ImageFont.truetype(used_font_path, current_size)
                except Exception:
                    pass
            
            if smaller_font is None:
                 smaller_font = ImageFont.load_default()
            
            bbox = draw.textbbox((0, 0), text, font=smaller_font)
            text_width = bbox[2] - bbox[0]
            
            if text_width <= target_width:
                return text, smaller_font
            
            current_size -= 2
        
        return text, smaller_font

    def find_common_font_size(texts, font, max_width):
        """Find the largest font size that fits all texts on one line."""
        current_size = font_size  # Start from the actual font_size, not 75%
        best_font = font
        min_font_size = max(20, int(font_size * 0.4))  # Don't go below 40% of font_size or 20px
        
        while current_size > min_font_size:
            test_font = None
            for font_path in font_paths:
                try:
                    test_font = ImageFont.truetype(font_path, current_size)
                    break
                except Exception:
                    continue
            
            if test_font is None:
                test_font = font
            
            # Check if all texts fit with this font size
            all_fit = True
            for text in texts:
                bbox = draw.textbbox((0, 0), text, font=test_font)
                text_width = bbox[2] - bbox[0]
                if text_width > max_width:
                    all_fit = False
                    break
            
            if all_fit:
                best_font = test_font
                break
            
            current_size -= 2
        
        return best_font

    # Colors
    color_word = (40, 40, 40)
    color_translation = (100, 100, 100) # This is the grey color for English translations
    color_sentence = (80, 80, 120)     # This is the color for the Finnish example sentence

    word_font_size = int(font_size * 2.0)  # Main word should be prominent but not overlapping
    word_font = None
    word_font = None
    if used_font_path:
        try:
            word_font = ImageFont.truetype(used_font_path, word_font_size)
        except Exception:
            pass
    
    if word_font is None:
        # Try to find any font if the used one failed for this size
         for font_path in font_paths:
            try:
                word_font = ImageFont.truetype(font_path, word_font_size)
                break
            except Exception:
                continue
    
    if word_font is None:
        word_font = font

    # Text positioning uses illustration_top and illustration_bottom calculated above
    # when we placed the scaled illustration
    text_bottom_padding = 15  # distance from the illustration to the translation text
    
    # Define max text width for wrapping
    max_text_width = img_width - (padding * 2)

    # Finnish word - Ensure it fits!
    _, word_font = fit_text_to_one_line(word, word_font, max_text_width, start_size=word_font_size)
    bbox_word = draw.textbbox((0, 0), word, font=word_font)
    word_width = bbox_word[2] - bbox_word[0]
    word_height = bbox_word[3] - bbox_word[1]

    # Translation - wrap if needed
    bbox_trans = draw.textbbox((0, 0), translation, font=font_small)
    translation_lines = wrap_text(translation, font_small, max_text_width)
    trans_line_height = bbox_trans[3] - bbox_trans[1]
    trans_total_height = trans_line_height * len(translation_lines) + (len(translation_lines) - 1) * 5
    
    # Total height of both Finnish word and translation with spacing
    spacing_between_lines = int(font_size * 0.8)  # Reduced spacing to fit in safe area
    two_line_height = word_height + spacing_between_lines + trans_total_height

    # Position text above illustration, ensuring it stays within safe area
    # Translation sits just above the illustration
    translation_y = illustration_top - text_bottom_padding - trans_total_height
    word_y = translation_y - word_height - spacing_between_lines
    
    # Ensure word doesn't go above safe margin
    if word_y < safe_margin_top + 10:
        word_y = safe_margin_top + 10
        translation_y = word_y + word_height + spacing_between_lines

    word_x = (img_width - word_width) // 2

    # Draw Finnish word
    draw.text((word_x, word_y), word, fill=color_word, font=word_font)
    
    # Draw translation lines (centered)
    current_y = translation_y
    for line in translation_lines:
        bbox_line = draw.textbbox((0, 0), line, font=font_small)
        line_width = bbox_line[2] - bbox_line[0]
        line_x = (img_width - line_width) // 2
        draw.text((line_x, current_y), line, fill=color_translation, font=font_small)
        current_y += trans_line_height + 5

    # Example sentences at the bottom - wrap both to use available white space
    
    # Wrap both Finnish and English example sentences to multiple lines using separate fonts if needed
    # Check if lines fit, if not shrink font
    
    def get_lines_and_font(text, start_font_size, max_w):
        current_s = start_font_size
        target_w = max_w * 0.95
        best_f = None
        final_lines = []
        
        while current_s > 10:
            # Load font
            test_f = None
            if used_font_path:
                try:
                    test_f = ImageFont.truetype(used_font_path, current_s)
                except: pass
            
            if test_f is None: test_f = ImageFont.load_default()
            
            # Wrap
            lines = wrap_text(text, test_f, max_w) # Wrap using full width
            
            # Check overflow of single words or lines against target width
            any_overflow = False
            for line in lines:
                bbox = draw.textbbox((0, 0), line, font=test_f)
                if (bbox[2] - bbox[0]) > target_w:
                    any_overflow = True
                    break
            
            if not any_overflow:
                return lines, test_f
            
            current_s -= 2
            
        return wrap_text(text, ImageFont.load_default(), max_w), ImageFont.load_default()

    initial_ex_size = int(font_size * 0.75)
    example_lines, font_example_fi = get_lines_and_font(example_sentence, initial_ex_size, max_text_width)
    example_trans_lines, font_example_en = get_lines_and_font(example_sentence_translation, initial_ex_size, max_text_width)
    
    # Calculate line height for example text
    bbox_test = draw.textbbox((0, 0), "Test", font=font_example)
    example_line_height = bbox_test[3] - bbox_test[1]
    line_spacing = 5  # Space between lines within same text block
    block_spacing = 20  # Space between Finnish and English blocks
    
    # illustration_bottom is already calculated when we placed the scaled illustration
    # Place example sentences below illustration, within the bottom text area
    gap_after_square = 15
    sentence_y = illustration_bottom + gap_after_square
    
    # Calculate max Y position to ensure text stays within safe area
    max_y = img_height - safe_margin_bottom - 10

    # Draw Finnish example sentence (centered, multi-line)
    current_y = sentence_y
    for line in example_lines:
        bbox_line = draw.textbbox((0, 0), line, font=font_example_fi)
        line_width = bbox_line[2] - bbox_line[0]
        line_x = (img_width - line_width) // 2
        draw.text((line_x, current_y), line, fill=color_sentence, font=font_example_fi)
        current_y += example_line_height + line_spacing
    
    # Add spacing between blocks
    current_y += block_spacing - line_spacing
    
    # Draw English example translation (centered, multi-line)
    # Only draw if we have room in the safe area
    for line in example_trans_lines:
        if current_y + example_line_height > max_y:
            break  # Stop if we'd exceed safe area
        bbox_line = draw.textbbox((0, 0), line, font=font_example_en)
        line_width = bbox_line[2] - bbox_line[0]
        line_x = (img_width - line_width) // 2
        draw.text((line_x, current_y), line, fill=color_translation, font=font_example_en)
        current_y += example_line_height + line_spacing

    try:
        img.save(output_path)
        print(f"✅ Saved image with text overlay: {output_path}")
        return True
    except Exception as e:
        print(f"❌ Error saving image {output_path}: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Add text overlay to illustrations using word data from generate_word_list.py.")
    parser.add_argument("--input-dir", default="illustrations", help="Input directory with illustration images.")
    parser.add_argument("--words-json", required=True, help="Path to words JSON file.")
    parser.add_argument("--output-dir", default="illustrations_with_text", help="Output directory for images with text overlay.")
    parser.add_argument("--font-size", type=int, default=24, help="Font size for text.")
    parser.add_argument("--padding", type=int, default=40, help="Padding around text.")
    args = parser.parse_args()

    input_dir = args.input_dir
    words_json = args.words_json
    output_dir = args.output_dir
    font_size = args.font_size
    padding = args.padding

    # Load word data
    print(f"➡️ Loading word data from {words_json}...")
    words_list = []
    words_data = {}
    try:
        with open(words_json, 'r', encoding='utf-8') as f:
            words_list = json.load(f)
            if isinstance(words_list, list):
                for item in words_list:
                    if isinstance(item, dict) and 'word' in item:
                        word = item['word'].lower()
                        # Clean up example sentence (remove parenthetical text)
                        raw_example = item.get('example', f'Tämä on {item["word"]}.')
                        clean_example = re.sub(r'\s*\(.*?\)', '', raw_example).strip()
                        
                        words_data[word] = {
                            'translation': item.get('translation', item['word']),
                            'example': clean_example,
                            'example_translation': item.get('example_translation', f'This is {item["word"]}.')
                        }
    except Exception as e:
        print(f"❌ Error loading words JSON {words_json}: {e}")
        return

    if not words_data:
        print("❌ No word data loaded. Cannot proceed.")
        return

    os.makedirs(output_dir, exist_ok=True)

    # Try to load mapping file created by illustration generator
    mapping = {}
    mapping_path = os.path.join(input_dir, "mapping.json")
    if os.path.exists(mapping_path):
        try:
            with open(mapping_path, 'r', encoding='utf-8') as f:
                mapping_list = json.load(f)
                # Create a mapping from filename to word
                for item in mapping_list:
                    filename = item.get('filename', '')
                    word = item.get('word', '')
                    if filename and word:
                        mapping[filename] = word
                print(f"✅ Loaded word->image mapping from {mapping_path} ({len(mapping)} entries)")
        except Exception as e:
            print(f"⚠️ Could not load mapping file: {e}")

    image_files = sorted([f for f in os.listdir(input_dir) if f.endswith(".png")])

    if not image_files:
        print(f"⚠️ No PNG files found in {input_dir}.")
        return

    print(f"📝 Found {len(words_data)} words and {len(image_files)} images.")
    
    # If we have a mapping, use it directly
    if mapping:
        for img_file in image_files:
            if img_file in mapping:
                word = mapping[img_file]
                input_path = os.path.join(input_dir, img_file)
                output_filename = f"final_{img_file}"
                output_path = os.path.join(output_dir, output_filename)
                
                print(f"Processing: {word} ({img_file})")
                add_text_overlay(input_path, word, output_path, words_data, font_size=font_size, padding=padding)
            else:
                print(f"⚠️ No mapping found for image: {img_file}")
    else:
        # Fallback: match by index if no mapping available
        for idx, img_file in enumerate(image_files):
            if idx >= len(words_list):
                print(f"⚠️ More images than words. Stopping at image {img_file}.")
                break

            word_item = words_list[idx]
            word = word_item.get('word', '') if isinstance(word_item, dict) else str(word_item)

            if not word:
                print(f"⚠️ Skipping image {img_file}: no word found at index {idx}.")
                continue

            input_path = os.path.join(input_dir, img_file)
            output_filename = f"final_{img_file}"
            output_path = os.path.join(output_dir, output_filename)

            print(f"Processing: {word} ({img_file})")
            add_text_overlay(input_path, word, output_path, words_data, font_size=font_size, padding=padding)


if __name__ == "__main__":
    main()