#!/usr/bin/env python3
"""
add_text_to_illustrations.py

Overlay text (Finnish word, English translation, example sentence) on generated illustrations.
The text data is read from a JSON file generated by generate_word_list.py.

Creates a new image with:
  - Finnish word above the illustration
  - English translation below the Finnish word
  - Example sentence below the illustration

Usage:
  python add_text_to_illustrations.py --input-dir illustrations --words-json scripts/words_food.json --output-dir illustrations_with_text
"""
import argparse
import json
import os
import re
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


def load_words_data(words_json_path: str) -> dict:
    """Load word data from JSON file generated by generate_word_list.py.
    Returns a dict mapping word -> {translation, example, example_translation}.
    """
    words_map = {}
    try:
        with open(words_json_path, 'r', encoding='utf-8') as f:
            words_list = json.load(f)
            if isinstance(words_list, list):
                for item in words_list:
                    if isinstance(item, dict) and 'word' in item:
                        word = item['word'].lower()
                        words_map[word] = {
                            'translation': item.get('translation', item['word']),
                            'example': item.get('example', f'Tämä on {item["word"]}.'),
                            'example_translation': item.get('example_translation', f'This is {item["word"]}.')
                        }
    except Exception as e:
        print(f"⚠️ Error loading words JSON {words_json_path}: {e}")
    return words_map


def add_text_overlay(
    image_path: str,
    word: str,
    output_path: str,
    words_data: dict,
    font_size: int = 24,
    padding: int = 40,
):
    """
    Add text overlay directly on the illustration image.
    """

    try:
        img = Image.open(image_path).convert("RGB")
    except Exception as e:
        print(f"❌ Error loading image {image_path}: {e}")
        return False

    # Image dimensions
    img_width, img_height = img.size

    # Get translation and example sentence
    word_lower = word.lower()
    if word_lower in words_data:
        translation = words_data[word_lower]['translation']
        example_sentence = words_data[word_lower]['example']
        example_sentence_translation = words_data[word_lower]['example_translation']
    else:
        translation = word
        example_sentence = f'Tämä on {word}.'
        example_sentence_translation = f'This is {word}.'

    draw = ImageDraw.Draw(img)

    # Try to load monospace font
    try:
        font = ImageFont.truetype("C:\\Windows\\Fonts\\consola.ttf", font_size)
        font_small = ImageFont.truetype("C:\\Windows\\Fonts\\consola.ttf", int(font_size * 0.85))
    except Exception:
        try:
            font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", font_size)
            font_small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", int(font_size * 0.85))
        except Exception:
            font = ImageFont.load_default()
            font_small = font


    def wrap_text(text, font, max_width):
        """Wrap text to fit within max_width. Returns list of lines."""
        words = text.split()
        lines = []
        current_line = []

        for word in words:
            current_line.append(word)
            line_text = " ".join(current_line)
            bbox = draw.textbbox((0, 0), line_text, font=font)
            line_width = bbox[2] - bbox[0]

            if line_width > max_width:
                current_line.pop()
                if current_line:
                    lines.append(" ".join(current_line))
                current_line = [word]

        if current_line:
            lines.append(" ".join(current_line))

        return lines

    def fit_text_to_one_line(text, font, max_width):
        """Adjust font size to fit text on one line, or return the text with smaller font."""
        bbox = draw.textbbox((0, 0), text, font=font)
        text_width = bbox[2] - bbox[0]
        
        if text_width <= max_width:
            return text, font
        
        # Try progressively smaller font sizes
        current_size = int(font_size * 0.75)
        while current_size > 8:
            try:
                smaller_font = ImageFont.truetype("C:\\Windows\\Fonts\\consola.ttf", current_size)
            except Exception:
                try:
                    smaller_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", current_size)
                except Exception:
                    smaller_font = font_small
            
            bbox = draw.textbbox((0, 0), text, font=smaller_font)
            text_width = bbox[2] - bbox[0]
            
            if text_width <= max_width:
                return text, smaller_font
            
            current_size -= 2
        
        return text, smaller_font

    def find_common_font_size(texts, font, max_width):
        """Find the largest font size that fits all texts on one line."""
        current_size = int(font_size * 0.75)
        best_font = font_small
        
        while current_size > 8:
            try:
                test_font = ImageFont.truetype("C:\\Windows\\Fonts\\consola.ttf", current_size)
            except Exception:
                try:
                    test_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", current_size)
                except Exception:
                    test_font = font_small
            
            # Check if all texts fit with this font size
            all_fit = True
            for text in texts:
                bbox = draw.textbbox((0, 0), text, font=test_font)
                text_width = bbox[2] - bbox[0]
                if text_width > max_width:
                    all_fit = False
                    break
            
            if all_fit:
                best_font = test_font
                break
            
            current_size -= 2
        
        return best_font

    # Colors
    color_word = (40, 40, 40)
    color_translation = (100, 100, 100) # This is the grey color for English translations
    color_sentence = (80, 80, 120)     # This is the color for the Finnish example sentence

    word_font_size = int(font_size * 1.5)
    try:
        word_font = ImageFont.truetype("C:\\Windows\\Fonts\\consola.ttf", word_font_size)
    except Exception:
        try:
            word_font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", word_font_size)
        except Exception:
            word_font = font

    # Calculate top of centered square illustration
    illustration_top = (img_height - img_width) // 2

    # Place text just ABOVE the square (adjust this value to fine-tune)
    text_bottom_padding = 20 # distance from the square to the translation text

    # Finnish word
    bbox_word = draw.textbbox((0, 0), word, font=word_font)
    word_width = bbox_word[2] - bbox_word[0]
    word_height = bbox_word[3] - bbox_word[1]

    # Translation
    bbox_trans = draw.textbbox((0, 0), translation, font=font_small)
    trans_width = bbox_trans[2] - bbox_trans[0]
    trans_height = bbox_trans[3] - bbox_trans[1]

    # Total height of both lines with spacing proportional to font size
    spacing_between_lines = int(font_size * 0.3)  # Dynamic spacing based on font size
    two_line_height = word_height + spacing_between_lines + trans_height

    # Final positions
    translation_y = illustration_top - text_bottom_padding - trans_height
    word_y = translation_y - word_height - spacing_between_lines

    word_x = (img_width - word_width) // 2
    trans_x = (img_width - trans_width) // 2

    # Draw them
    draw.text((word_x, word_y), word, fill=color_word, font=word_font)
    # English word translation (Grey)
    draw.text((trans_x, translation_y), translation, fill=color_translation, font=font_small)

    # Example sentence at the bottom
    max_text_width = img_width - (padding * 2)
    
    # Find a common font size that fits both example sentences on single lines
    common_font = find_common_font_size([example_sentence, example_sentence_translation], font_small, max_text_width)

    # Calculate positions for bottom text (closer to the square image)
    line_height = int(font_size * 0.85) + 8
    total_height = line_height * 2
    
    # Calculate the square illustration bottom position
    illustration_bottom = illustration_top + img_width
    
    # Place example sentences closer to the square (reduced gap)
    gap_after_square = 15  # Reduced gap from square to text
    sentence_y = illustration_bottom + gap_after_square

    # Center the example sentence
    bbox_example = draw.textbbox((0, 0), example_sentence, font=common_font)
    example_width = bbox_example[2] - bbox_example[0]
    example_x = (img_width - example_width) // 2
    draw.text((example_x, sentence_y), example_sentence, fill=color_sentence, font=common_font)

    # Center the example translation
    bbox_trans_example = draw.textbbox((0, 0), example_sentence_translation, font=common_font)
    example_trans_width = bbox_trans_example[2] - bbox_trans_example[0]
    example_trans_x = (img_width - example_trans_width) // 2
    draw.text((example_trans_x, sentence_y + line_height), example_sentence_translation, fill=color_translation, font=common_font)

    try:
        img.save(output_path)
        print(f"✅ Saved image with text overlay: {output_path}")
        return True
    except Exception as e:
        print(f"❌ Error saving image {output_path}: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Add text overlay to illustrations using word data from generate_word_list.py.")
    parser.add_argument("--input-dir", default="illustrations", help="Input directory with illustration images.")
    parser.add_argument("--words-json", required=True, help="Path to words JSON file.")
    parser.add_argument("--output-dir", default="illustrations_with_text", help="Output directory for images with text overlay.")
    parser.add_argument("--font-size", type=int, default=24, help="Font size for text.")
    parser.add_argument("--padding", type=int, default=40, help="Padding around text.")
    args = parser.parse_args()

    input_dir = args.input_dir
    words_json = args.words_json
    output_dir = args.output_dir
    font_size = args.font_size
    padding = args.padding

    # Load word data
    print(f"➡️ Loading word data from {words_json}...")
    words_list = []
    words_data = {}
    try:
        with open(words_json, 'r', encoding='utf-8') as f:
            words_list = json.load(f)
            if isinstance(words_list, list):
                for item in words_list:
                    if isinstance(item, dict) and 'word' in item:
                        word = item['word'].lower()
                        words_data[word] = {
                            'translation': item.get('translation', item['word']),
                            'example': item.get('example', f'Tämä on {item["word"]}.'),
                            'example_translation': item.get('example_translation', f'This is {item["word"]}.')
                        }
    except Exception as e:
        print(f"❌ Error loading words JSON {words_json}: {e}")
        return

    if not words_data:
        print("❌ No word data loaded. Cannot proceed.")
        return

    os.makedirs(output_dir, exist_ok=True)

    # Try to load mapping file created by illustration generator
    mapping = {}
    mapping_path = os.path.join(input_dir, "mapping.json")
    if os.path.exists(mapping_path):
        try:
            with open(mapping_path, 'r', encoding='utf-8') as f:
                mapping_list = json.load(f)
                # Create a mapping from filename to word
                for item in mapping_list:
                    filename = item.get('filename', '')
                    word = item.get('word', '')
                    if filename and word:
                        mapping[filename] = word
                print(f"✅ Loaded word->image mapping from {mapping_path} ({len(mapping)} entries)")
        except Exception as e:
            print(f"⚠️ Could not load mapping file: {e}")

    image_files = sorted([f for f in os.listdir(input_dir) if f.endswith(".png")])

    if not image_files:
        print(f"⚠️ No PNG files found in {input_dir}.")
        return

    print(f"📝 Found {len(words_data)} words and {len(image_files)} images.")
    
    # If we have a mapping, use it directly
    if mapping:
        for img_file in image_files:
            if img_file in mapping:
                word = mapping[img_file]
                input_path = os.path.join(input_dir, img_file)
                output_filename = f"final_{img_file}"
                output_path = os.path.join(output_dir, output_filename)
                
                print(f"Processing: {word} ({img_file})")
                add_text_overlay(input_path, word, output_path, words_data, font_size=font_size, padding=padding)
            else:
                print(f"⚠️ No mapping found for image: {img_file}")
    else:
        # Fallback: match by index if no mapping available
        for idx, img_file in enumerate(image_files):
            if idx >= len(words_list):
                print(f"⚠️ More images than words. Stopping at image {img_file}.")
                break

            word_item = words_list[idx]
            word = word_item.get('word', '') if isinstance(word_item, dict) else str(word_item)

            if not word:
                print(f"⚠️ Skipping image {img_file}: no word found at index {idx}.")
                continue

            input_path = os.path.join(input_dir, img_file)
            output_filename = f"final_{img_file}"
            output_path = os.path.join(output_dir, output_filename)

            print(f"Processing: {word} ({img_file})")
            add_text_overlay(input_path, word, output_path, words_data, font_size=font_size, padding=padding)


if __name__ == "__main__":
    main()